name: Assembly CI

on:
  push:
    branches: [ "main" ]

jobs:
  Test:

    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '[TEST]') }}
    
    steps:
      - uses: actions/cache@v3
        with:
          path: ~/nasm
          key: nasm-2.15.05
      - name: Setup nasm
        if: steps.cache.outputs.cache-hit != 'true'
        uses: ilammy/setup-nasm@v1

      - uses: actions/checkout@v3
      - name: build my_tests
        run: |
          mkdir build
          cd build
          cmake ..
          make my_tests
      - name: my_tests
        run: ./build/my_tests