name: Assembly CI

on:
  push:
    branches: [ "main" ]

jobs:
  Test:

    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, '#TEST') }}
    
    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v3
      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          make my_tests
      - name: my_tests
        run: ./build/my_tests
